# Generated by Django 6.0.3 on 2026-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='上传附件'),
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='插入图片'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='插入视频'),
        ),
    ]
