# Generated by Django 6.0.3 on 2026-04-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_document_entry_image_entry_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公开笔记'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公开主题'),
        ),
    ]
