# Generated by Django 6.0.3 on 2026-04-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_content_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(choices=[('briefing_release', '晨报发布'), ('artifact_release', '执行结果发布')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私有'), ('mixed', '混合')], db_index=True, default='private', max_length=20)),
                ('source_object_ids', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_items', to=settings.AUTH_USER_MODEL)),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_items', to='learning_logs.entry')),
            ],
            options={
                'verbose_name': '信息流条目',
                'verbose_name_plural': '信息流条目',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
