# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_streamitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamitem',
            name='visibility',
            field=models.CharField(
                choices=[('public', '公开'), ('private', '私有'), ('mixed', '混合')],
                db_index=True,
                default='public',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='streamitem',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stream_items',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
