# Generated by Django 6.0.3 on 2026-05-01 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_system_stream_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamitem',
            name='event_type',
            field=models.CharField(choices=[('briefing_release', '晨报发布'), ('artifact_release', '执行结果发布'), ('signal_item', '高价值信号'), ('theme_update', '主题跟踪'), ('action_result', '最小落地结果')], db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='streamitem',
            index=models.Index(fields=['visibility', 'event_type', 'occurred_at', 'id'], name='stream_public_feed_idx'),
        ),
    ]
